### ISSUE TITLE
Add possibility of passing artifact registry credentials to docker build

### ISSUE THREAD

**Issue by nils1k** [entur/gha-docker#123]
**Is your feature request related to a problem? Please describe.**
We build our application using a multi-stage Docker build and have a dependency on artefacts residing in an internal registry. Currently, it is not supported to pass credentials to the `docker/build-push-action` in the [shared workflow build](https://github.com/entur/gha-docker/blob/main/.github/workflows/build.yml#L111), i.e. the action itself supports it, but it is not among the supported inputs in this workflow.

**Describe the solution you'd like**
I want to be able to pass custom arguments to the docker build through the [build-args input](https://github.com/docker/build-push-action?tab=readme-ov-file#inputs) in `docker/build-push-action`. Here is an example:

`Dockerfile`
```yml
# Dockerfile
ARG REGISTRY_USER
ARG REGISTRY_APIKEY

COPY src /app/src
COPY build.gradle.kts settings.gradle.kts /app/
RUN gradle build
```

`build.gradle.kts`
```kotlin
repositories {
	maven {
		setUrl("myRegistry")
		credentials {
			username = System.getenv("REGISTRY_USER")
			password = System.getenv("REGISTRY_APIKEY")
		}
	}
}
```

`build.yml`
```yml
name: build
on: [push, pull_request]

env:
  REGISTRY_USER: '${{ secrets.REGISTRY_USER }}'
  ARTIFACTORY_APIKEY: '${{ secrets.REGISTRY_APIKEY }}'

jobs:
  build:
    name: Build application
    needs: lint
    uses: entur/gha-docker/.github/workflows/build.yml@v1.3.8
    with:
      build-args: |
        --build-arg REGISTRY_USER=${REGISTRY_USER}
        --build-arg REGISTRY_APIKEY=${REGISTRY_APIKEY}
```

**Describe alternatives you've considered**
Use [secret mounts](https://docs.docker.com/build/ci/github-actions/secrets/#secret-mounts).

**Additional context**
N/A
