### ISSUE TITLE
Use correct SHA for feature builds (when pull_request trigger)

### ISSUE THREAD

**Issue by AlexanderBrevig** [entur/gha-docker#85]
Probably needs a fix here (maybe checking out HEAD^?)

https://github.com/entur/gha-docker/blob/1d714c9bfe236d7705a304e5a6bab7f897633b97/.github/workflows/push.yml#L73-L77

**Comment by elg-entur** [comment]
Fikset med 
```yaml
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
```
